config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :activities
  resources :machines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'activities#index'
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/machine.rb
# frozen_string_literal: true

class Machine < ApplicationRecord
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy]

  # GET /activities
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  def show
    render Activities::Show.new(activity: @activity)
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to @activity, notice_sucess: notice_sucess(Activity, :create)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice_sucess: notice_sucess(Activity, :update)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice_sucess: notice_sucess(Activity, :destroy), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:name, :co2_kg)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Localization

  private

  def notice_sucess(klass, action)
    t("activerecord.action_messages.success", action: action, resource: klass.name)
  end
end

app/controllers/concerns/localization.rb
# frozen_string_literal: true

module Localization
  extend ActiveSupport::Concern

  included do
    around_action :switch_locale

    protected

    def switch_locale(&action)
      locale = extract_locale_from_param || I18n.default_locale

      I18n.with_locale(locale, &action)
    end

    def extract_locale_from_param
      return params[:locale] if I18n.locale_available?(params[:locale])

      nil
    end

    private

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
  end
end

app/controllers/machines_controller.rb
# frozen_string_literal: true

class MachinesController < ApplicationController
  before_action :set_machine, only: %i[show edit update destroy]

  # GET /machines
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  def show; end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit; end

  # POST /machines
  def create
    @machine = Machine.new(machine_params)

    if @machine.save
      redirect_to @machine, notice_snotice_sucess notice_sucess(Machine, :create)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /machines/1
  def update
    if @machine.update(machine_params)
      redirect_to @machine, notice_sucess: notice_sucess(Machine, :update)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /machines/1
  def destroy
    @machine.destroy
    redirect_to machines_url, notice_sucess: notice_sucess(Machine, :destroy), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_machine
    @machine = Machine.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def machine_params
    params.require(:machine).permit(:name, :yearly_co2_kg)
  end
end

app/helpers/activities_helper.rb
# frozen_string_literal: true

module ActivitiesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/machines_helper.rb
# frozen_string_literal: true

module MachinesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :co2_kg, style: "display: block" %>
    <%= form.text_field :co2_kg %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <div class="mb-4">
      <%= render(CardComponent.new(title: 'Activity', sub_title: activity.name)) do %>
        <p>Hello, World!</p>
        <%= link_to 'Show this activity', activity, class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to "New activity", new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <title>Impact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/_form.html.erb
<%= form_with(model: machine) do |form| %>
  <% if machine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
        <% machine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :yearly_co2_kg, style: "display: block" %>
    <%= form.text_field :yearly_co2_kg %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<div id="<%= dom_id machine %>">
  <p>
    <strong>Name:</strong>
    <%= machine.name %>
  </p>

  <p>
    <strong>Yearly co2 tons:</strong>
    <%= machine.yearly_co2_kg %>
  </p>

</div>

app/views/machines/edit.html.erb
<h1>Editing machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Show this machine", @machine %> |
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Machines</h1>

<div id="machines">
  <% @machines.each do |machine| %>
    <%= render machine %>
    <p>
      <%= link_to "Show this machine", machine %>
    </p>
  <% end %>
</div>

<%= link_to "New machine", new_machine_path %>

app/views/machines/new.html.erb
<h1>New machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @machine %>

<div>
  <%= link_to "Edit this machine", edit_machine_path(@machine) %> |
  <%= link_to "Back to machines", machines_path %>

  <%= button_to "Destroy this machine", @machine, method: :delete %>
</div>